// vue/hello-mint/src/App.vue
<template>
  <div>
    <h1>Hello, Griptape!</h1>
    <button @click="connect">Connect</button>
    <button @click="mint">{{loadingMint ? 'Loading...' : 'Mint'}}</button>
    <br />
    <br />
    <button @click="getTokens">
      {{loadingTokens ? 'Loading...' : 'Get Tokens'}}
    </button>
    <button @click="createViewingKey">
      {{loading ? 'Loading...' : 'Create Viewing Key'}}
    </button>
    <br />
    <div v-bind:key="item.name" v-for="item in tokens">
      <div>
        <img v-if="item.image" :src="item.image" alt="[image]" />
        <img
          v-else
          src="https://i.picsum.photos/id/551/200/300.jpg?hmac=pXJCWIikY_BiqwhtawBb8x1jxclDny0522ZprZVTJiU"
          alt="[image]"
        />
      </div>
      <div>{{item.name}}</div>
    </div>
  </div>
</template>

<script>
import {
  viewingKeyManager,
  bootstrap
} from '@stakeordie/griptape.js';
import { minting } from './contracts/minting';

export default {
  data() {
    return {
      loading: false,
      loadingMint:false,
      loadingTokens:false,
      tokens:[]
    }
  },
  methods: {
    async createViewingKey  () {
      this.loading = true;
      try {
        const result = await minting.createViewingKey();

        if (result.isEmpty()) return;

        const { viewing_key: { key } } = result.parse();
        viewingKeyManager.add(minting, key);
      } catch (e) {
        console.error(e)
      } finally {
        this.loading = false;
      }
    },
    async connect() {
      await bootstrap();
    },
    async mint(){
      var date = Date.now();
      const data = {
        name: `Example ${date}`,
        description: "test",
        image: 'https://i.picsum.photos/id/586/200/300.jpg?hmac=Ugf94OPRVzdbHxLu5sunf4PTa53u3gDVzdsh5jFCwQE'
      }
      this.loadingMint = true;
      try {
        const mint = await minting.mintNft(data);
      } catch (e) {
        // ignore for now
      } finally {
        this.loadingMint = false;
      }
  },
  async getTokens(){
    this.loadingTokens = true;
    try {
      //Get list of tokens' id owned
      // Exam. ["4","65","87"]
      const tokens = await minting.getTokens();
      const token_list = tokens.token_list.tokens;
      //Get details of each token
      await this.getNftDetail(token_list);
    } catch (e) {
      console.error(e)
    } finally {
      this.loadingTokens = false;
    }
  },
  async getNftDetail(token_list) {
    const promises = token_list.map(token => {
      //Query each token 
      return minting.getNftDossier(token);
    });

    const result = await Promise.allSettled(promises);
    this.tokens = result
      .filter(item => item.status === 'fulfilled')
      .map(item => item.value.nft_dossier)
      .map(({ public_metadata: { extension } }) => ({
        name: extension.name,
        description: extension.description,
        image: extension.image
      }));
    }
  }
}
</script>

// react/hello-mint/src/App.js
import React, { useState, useEffect } from "react";
import {
  bootstrap,
  viewingKeyManager,
  onAccountAvailable
} from '@stakeordie/griptape.js';
import { minting } from './contracts/minting';
import TokenList from "./components/TokenList";

function App() {

  var [loading, setLoading] = useState(false);
  var [loadingMint, setLoadingMint] = useState(false);
  var [loadingTokens, setLoadingTokens] = useState(false);
  var [viewingKey, setViewingKey] = useState('');
  var [nftList, setNftList] = useState([]);

  useEffect(() => {
    onAccountAvailable(() => {
      const key = viewingKeyManager.get(minting.at);
      if (key) {
        setViewingKey(key);
      }
    })
  }, []);

  const connect = async () => {
    await bootstrap();
  }

  const mint = async () => {

    var date = Date.now();

    const data = {
      name: `Example ${date}`,
      description: "test",
      image: 'https://i.picsum.photos/id/586/200/300.jpg?hmac=Ugf94OPRVzdbHxLu5sunf4PTa53u3gDVzdsh5jFCwQE'
    }

    setLoadingMint(true);
    try {
      const mint = await minting.mintNft(data);

    } catch (e) {
      // ignore for now
    } finally {
      setLoadingMint(false);
    }

  }

  const getTokens = async () => {

    setLoadingTokens(true);
    try {
      const tokens = await minting.getTokens();
      const token_list = tokens.token_list.tokens;
      await getNftDetail(token_list);

    } catch (e) {
      // ignore for now
    } finally {
      setLoadingTokens(false);
    }
  }

  const getNftDetail = async (token_list) => {
    const promises = token_list.map(token => {
      return minting.getNftDossier(token);
    });

    const result = await Promise.allSettled(promises);
    const tokens = result
      .filter(item => item.status === 'fulfilled')
      .map(item => item.value.nft_dossier)
      .map(({ public_metadata: { extension } }) => ({
        name: extension.name,
        description: extension.description,
        image: extension.image
      }));

    setNftList(tokens);
  }

  const createViewingKey = async () => {

    setLoading(true);
    try {
      const result = await minting.createViewingKey();

      if (result.isEmpty()) return;

      const { viewing_key: { key } } = result.parse();
      viewingKeyManager.add(minting, key);
      setViewingKey(key);

      const currentKey = viewingKeyManager.get(minting.at);

      if (currentKey) {
        viewingKeyManager.set(minting, key);
      } else {
        viewingKeyManager.add(minting, key);
      }

    } catch (e) {
      console.error(e)
    } finally {

      setLoading(false);
    }

  }


  return (
    <>
      <h1>Hello, Griptape!</h1>
      <button onClick={() => { connect(); }}>Connect</button>
      <button onClick={() => { mint(); }}>{loadingMint ? 'Loading...' : 'Mint'}</button>
      <br></br>
      <br></br>
      <button onClick={() => { getTokens(); }}>{loadingTokens ? 'Loading...' : 'Get Tokens'}</button>
      <button onClick={() => { createViewingKey(); }}>{loading ? 'Loading...' : 'Create Viewing Key'}</button>
      <br></br>
      <TokenList nftList={nftList} />
    </>
  );
}

export default App;
