// vue/contract-griptape-vue/src/App.vue
<template>
  <div>
    <h1>Hello, Griptape!</h1>
    <p>Your count is: {{ count }}</p>
    <button @click="connect">Connect</button>
    <button @click="getCount">Get count</button>
    <button @click="incrementCount">
      <span v-if="loading">Loading...</span>
      <span v-else>Increment by 1</span>
    </button>
  </div>
</template>

<script>
import { counterContract } from './contracts/counter';
import { bootstrap } from '@stakeordie/griptape.js';

export default {
  data: () => ({
    count: '',
    loading: false
  }),

  methods: {
    async getCount() {
      const response = await counterContract.getCount();
      this.count = response.count;
    },
    async connect() {
      await bootstrap();
    },

    async incrementCount() {
      this.loading = true;
      await counterContract.incrementCount();
      this.loading = false;
    }
  }
}
</script>

// react/hello-contracts/src/App.js
import React, { useState } from "react";
import { counterContract } from './contracts/counter';
import { bootstrap } from "@stakeordie/griptape.js";

function App() {

  const [count, setCount] = useState('');
  const [loading, setLoading] = useState(false);

  const getCount = async () => {
    const response = await counterContract.getCount();
    setCount(response.count);
  }

  const connect = async () => {
    await bootstrap();
  }

  const incrementCount = async () => {
    setLoading(true);
    await counterContract.incrementCount();
    setLoading(false);
    return await counterContract.incrementCount();
  }

  return (
    <>
      <h1>Hello, Griptape!</h1>
      <p>Your count is: {count}</p>
      <button onClick={() => { connect(); }}>Connect</button>
      <button onClick={() => { getCount() }}>Get count</button>
      <button onClick={() => { incrementCount() }}>{loading ? 'Loading...' : 'Increment by 1'}</button>
    </>
  );
}

export default App;
